### PR TITLE
Fix issue with shift + click row range selection in the query tool data output window

### LINKED ISSUE #5266: [REGRESSION] Shift+Click in Results Grid not working to select multiple cells (RM #7628)
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7628***
*Originally created by **Jona Raphael** at 2022-08-19 23:23:50 UTC.*

Hello,
I want to start off by expressing my gratitude for the work your team puts in--what a great thing you've created!

Recently, I updated my pgAdmin to the newest version (6.13), and was stymied by an apparent regression.

Previously, when you wanted to grab multiple results from the Query Tool Results Grid (e.g. for copying out of the application), you could do it many ways:
1) Click one or more headers to select whole columns
2) Click one or more indices to select whole rows
3) Click and drag to select adjacent cells
4) Click on one cell, then Shift+Click on another cell to select all intermediate cells

Now, options [1,2,3] still work, but option [4] is broken. Instead of selecting multiple, it only selects the second cell.

Is there any chance that this is a simple fix that you can patch quickly?

Best regards,
Jona

### PR DESCRIPTION
**Pull request by KijongHan**
Resolves https://github.com/pgadmin-org/pgadmin4/issues/5266

# What does this PR do?
This PR resolves an apparent regression where selecting a range of rows in the query tool data output window using shift+click was no longer functional in the new pgAdmin (range selection had been recently introduced to the [react-data-grid](https://github.com/adazzle/react-data-grid) repository and the following migration of that functionality to the pgAdmin fork

# Summary of changes
- set `isShiftClick` property to `useRowSelection` react hook update function
- set `rangeSelectionMode` property to data grid components to propagate shift click behaviour to the `selectedRows` react hook under `ResultSet.jsx`

### CODE REVIEW

File: web/pgadmin/static/js/components/PgReactDataGrid.jsx [hunk 1]
```diff
@@ -119,7 +119,7 @@ export function CustomRow({inTest=false, ...props}) {
 
   return (
     <Row {...props} onKeyDown={handleKeyDown} onCellClick={onCellClick} onCellDoubleClick={onCellDoubleClick}
-      selectCell={(row, column)=>props.selectCell(row, column)} aria-selected={isRowSelected}/>
+      selectCell={(row, column)=>props.selectCell(row, column)} aria-selected={isRowSelected} rangeSelectionMode={true}/>
```
Comment (adityatoshniwal) [inline web/pgadmin/static/js/components/PgReactDataGrid.jsx:122]: PgReactDataGrid is a common component and rangeSelectionMode true is not required here. rangeSelectionMode is only required in query tool grid.

File: web/pgadmin/static/js/components/PgReactDataGrid.jsx [hunk 2]
```diff
@@ -158,6 +158,7 @@ export default function PgReactDataGrid({gridRef, className, hasSelectColumn=tru
           renderSortStatus,
           noRowsFallback: <Box textAlign="center" gridColumn="1/-1" p={1}>{noRowsIcon}{noRowsText || gettext('No rows found.')}</Box>,
         }}
+        enableRangeSelection={true}
```
Comment (adityatoshniwal) [inline web/pgadmin/static/js/components/PgReactDataGrid.jsx:161]: Same as above. You should not change the common component default behaviour.

File: web/pgadmin/tools/sqleditor/static/js/components/QueryToolDataGrid/index.jsx [hunk 3]
```diff
@@ -116,7 +116,7 @@ function CustomRow(props) {
   };
   return (
     <RowInfoContext.Provider value={rowInfoValue}>
-      <Row ref={rowRef} onKeyDown={handleKeyDown} {...props} />
+      <Row ref={rowRef} onKeyDown={handleKeyDown} {...props} rangeSelectionMode={true}/>
```
Comment (adityatoshniwal) [inline web/pgadmin/tools/sqleditor/static/js/components/QueryToolDataGrid/index.jsx:119]: there is no such prop rangeSelectionMode on Row component.

**Review by adityatoshniwal — CHANGES_REQUESTED** [review]

File: web/pgadmin/static/js/components/PgReactDataGrid.jsx (hunk 1 above)
Comment (KijongHan) [reply web/pgadmin/static/js/components/PgReactDataGrid.jsx]: thanks for looking into this @adityatoshniwal - that was careless on my part. have updated so that it is only enabled from query tool component via `prop.enableRangeSelection`

File: web/pgadmin/static/js/components/PgReactDataGrid.jsx (hunk 2 above)
Comment (KijongHan) [reply web/pgadmin/static/js/components/PgReactDataGrid.jsx]: yeah agree thanks - have updated so its set via `prop.enableRangeSelection`

File: web/pgadmin/tools/sqleditor/static/js/components/QueryToolDataGrid/index.jsx (hunk 3 above)
Comment (KijongHan) [reply web/pgadmin/tools/sqleditor/static/js/components/QueryToolDataGrid/index.jsx]: fixed, thanks

File: web/pgadmin/static/js/components/PgReactDataGrid.jsx [hunk 4]
```diff
@@ -119,7 +119,7 @@ export function CustomRow({inTest=false, ...props}) {
 
   return (
     <Row {...props} onKeyDown={handleKeyDown} onCellClick={onCellClick} onCellDoubleClick={onCellDoubleClick}
-      selectCell={(row, column)=>props.selectCell(row, column)} aria-selected={isRowSelected}/>
+      selectCell={(row, column)=>props.selectCell(row, column)} aria-selected={isRowSelected} rangeSelectionMode={props.enableRangeSelection}/>
```
Comment (adityatoshniwal) [inline web/pgadmin/static/js/components/PgReactDataGrid.jsx:122]: this is not needed.

**Review by adityatoshniwal — CHANGES_REQUESTED** [review]
While it fixes shift row selection, it doesn't work for columns and cell range selection.
I think it is a partial fix.

File: web/pgadmin/static/js/components/PgReactDataGrid.jsx (hunk 4 above)
Comment (KijongHan) [reply web/pgadmin/static/js/components/PgReactDataGrid.jsx]: thanks, done - I can see that `rangeSelectionMode` is mostly used as to determine the cell range selection in the underlying library, but I'm a little puzzled as to how the cell range selection is working atm without this being toggled active

Comment (adityatoshniwal) [reply web/pgadmin/static/js/components/PgReactDataGrid.jsx]: that is taken care at the DataGrid main component level. subcomponents don't need the prop to be passed explicitly.

**Comment by adityatoshniwal** [comment]
Hi @KijongHan,

It would be great to fix in the same PR if you can. That way we can close #5266. Otherwise, it will remain open until other things are fixed.

**Comment by KijongHan** [comment]
> Hi @KijongHan,
> 
> It would be great to fix in the same PR if you can. That way we can close #5266. Otherwise, it will remain open until other things are fixed.

Cool, Ill see what can be done @adityatoshniwal . I just updated the PR to introduce similar behaviour for shift+clicking through column selection if you could please review those changes

**Comment by adityatoshniwal** [comment]
> Cool, Ill see what can be done @adityatoshniwal . I just updated the PR to introduce similar behaviour for shift+clicking through column selection if you could please review those changes

@KijongHan  Nice! So rows and columns are done. Cell range remains. Do you want to fix it?

**Comment by KijongHan** [comment]
> > Cool, Ill see what can be done @adityatoshniwal . I just updated the PR to introduce similar behaviour for shift+clicking through column selection if you could please review those changes
> 
> @KijongHan Nice! So rows and columns are done. Cell range remains. Do you want to fix it?

Hey @adityatoshniwal - sorry didnt have too much time over the last few weeks to look into it and Im currently on holiday at the moment, if its okay with you we can merge these in minus the cell range fix?

**Comment by adityatoshniwal** [comment]
> > > Cool, Ill see what can be done @adityatoshniwal . I just updated the PR to introduce similar behaviour for shift+clicking through column selection if you could please review those changes
> > 
> > 
> > @KijongHan Nice! So rows and columns are done. Cell range remains. Do you want to fix it?
> 
> Hey @adityatoshniwal - sorry didnt have too much time over the last few weeks to look into it and Im currently on holiday at the moment, if its okay with you we can merge these in minus the cell range fix?

OK. No problem.
